#!/usr/bin/env bash
# Handle SIGTERM signal
trap 'echo "I am invincible!!!"; echo OK' SIGTERM

# Infinite loop with message and sleep
while true
do
    echo "To infinity and beyond"
    sleep 2
done

